# Generated by Django 6.0.3 on 2026-04-01 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('term', models.CharField()),
                ('definition', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flowcard', to='library.librarycontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowcards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
