# Generated by Django 6.0.2 on 2026-04-28 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowcard',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flowcard', to='library.librarycontent'),
        ),
    ]
