# Generated by Django 6.0.2 on 2026-05-12 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_alter_flowcard_library'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowcard',
            name='definition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flowcard',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='flowcard',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='flowcard',
            name='term',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='flowcard',
            unique_together={('user', 'name')},
        ),
    ]
