version: "3.9"

services:
  backend:
    build: ./Backend
    container_name: django
    restart: always
    expose:
      - "8000"

  frontend:
    build: ./Frontend
    container_name: vue
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf.prod:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
