services:
  backend:
    build: ./Backend
    container_name: django
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"

  frontend:
    build: ./Frontend
    container_name: vue
    ports:
      - "80:80"
    depends_on:
      - backend
