[project]
name = "knowflow"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "crispy-bootstrap5>=2025.6",
    "django>=6.0.2",
    "django-browser-reload>=1.21.0",
    "django-colorfield>=0.14.0",
    "django-cors-headers>=4.9.0",
    "django-rq>=3.2.2",
    "django-webpack-loader>=3.2.3",
    "factory-boy>=3.3.3",
    "nodejs>=0.1.1",
    "pillow>=12.1.0",
    "prettyconf>=2.3.0",
    "prettyconfig>=0.0.1",
    "pytest>=9.0.2",
    "pytest-django>=4.12.0",
    "sorl-thumbnail>=13.0.0",
    "zensical>=0.0.21",
]

[dependency-groups]
dev = [
    "django-browser-reload>=1.21.0",
    "watchdog>=6.0.0",
    "zensical>=0.0.21",
]
