[project]
name = "knowflow"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "crispy-bootstrap5>=2025.6",
    "django>=6.0.2",
    "django-colorfield>=0.14.0",
    "django-rq>=3.2.2",
    "pillow>=12.1.0",
    "sorl-thumbnail>=13.0.0",
]

[dependency-groups]
dev = [
    "django-browser-reload>=1.21.0",
    "watchdog>=6.0.0",
]
