# Generated by Django 6.0.2 on 2026-05-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskflow_options_taskflow_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskflow',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
