# Generated by Django 6.0.2 on 2026-05-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowtionaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowtionary',
            name='max_score_per_question',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
