# Generated by Django 6.0.2 on 2026-05-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=20),
        ),
    ]
