# Generated by Django 6.0.2 on 2026-05-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_role_profile_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('M', 'Member'), ('K', 'Knower')], default='M', max_length=1),
        ),
    ]
