# Generated by Django 6.0.2 on 2026-02-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knowtionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True)),
                ('question', models.CharField()),
                ('answer', models.CharField()),
                ('image', models.ImageField(upload_to='', verbose_name=models.ImageField(blank=True, default='media/default.png', null=True, upload_to='media'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
